<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://example" xmlns:apachesoap="http://xml.apache.org/xml-soap"
                  xmlns:impl="http://example" xmlns:intf="http://example" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://xml.apache.org/xml-soap ">
    <!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
    <wsdl:types>
        <schema elementFormDefault="qualified" targetNamespace="http://example"
                xmlns="http://www.w3.org/2001/XMLSchema">
            <element name="from" type="xsd:string"/>
            <element name="sayHelloWorldFromReturn" type="xsd:string"/>
        </schema>
    </wsdl:types>

    <wsdl:message name="sayHelloWorldFromResponse">

        <wsdl:part element="impl:sayHelloWorldFromReturn" name="sayHelloWorldFromReturn"/>

    </wsdl:message>

    <wsdl:message name="sayHelloWorldFromRequest">

        <wsdl:part element="impl:from" name="from"/>

    </wsdl:message>

    <wsdl:portType name="HelloWorld">

        <wsdl:operation name="sayHelloWorldFrom" parameterOrder="from">

            <wsdl:input message="impl:sayHelloWorldFromRequest" name="sayHelloWorldFromRequest"/>

            <wsdl:output message="impl:sayHelloWorldFromResponse" name="sayHelloWorldFromResponse"/>

        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="HelloWorldSoapBinding" type="impl:HelloWorld">

        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="sayHelloWorldFrom">

            <wsdlsoap:operation soapAction=""/>

            <wsdl:input name="sayHelloWorldFromRequest">

                <wsdlsoap:body use="literal"/>

            </wsdl:input>

            <wsdl:output name="sayHelloWorldFromResponse">

                <wsdlsoap:body use="literal"/>

            </wsdl:output>

        </wsdl:operation>

    </wsdl:binding>

    <wsdl:service name="HelloWorldService">

        <wsdl:port binding="impl:HelloWorldSoapBinding" name="HelloWorld">

            <wsdlsoap:address location="http://localhost:8080/services/example/HelloWorld"/>

        </wsdl:port>

    </wsdl:service>

</wsdl:definitions>
